### PR TITLE
Adds support for field filtering.

### PR DESCRIPTION
**Pull request by jyliang**

### CODE REVIEW

**Comment by joshuapinter** [comment]
Wow, this looks like a great update. Thanks!

Since it's such a big change, I'd like to get some tests in there before merging. Any chance you can write some basics tests for those new methods?

**Comment by jyliang** [comment]
cool, i'll try to get some in after the holidays. happy holidays btw!

**Comment by joshuapinter** [comment]
@jyliang Awesome, and likewise!!

**Comment by paintedbicycle** [comment]
Hey @jyliang this feature is exciting. Are you able to bring in some of the more recent changes from the master branch since your PR and then thoroughly test it? Would love to see this merge.

Also, we've updated the Android branch, so this feature would be a good one to also have over there as we're starting to get to a point where we can bring Android support to master.

**Comment by bradennapier** [comment]
Was just about to ask about this functionality.  Nice work @jyliang although its almost a year old now heh

**Pull request closed without merging**
