### PR TITLE
update to latest swift syntax

### PR DESCRIPTION
**Pull request by chrise86**
Fixes issues with latest Xcode (8.3).

Also adds `getGroups` method:

```
Contacts.getGroups( (error, groups) =>  {
  if (error) {
    console.error(error);
  }
  else {
    console.log(groups);
  }
});
```

### CODE REVIEW

**Comment by joshuapinter** [comment]
@chrise86 Damn, that was fast. Haha.

I'll have to test it when I'm back. Is this backwards compatible or a breaking change that requires XCode 8.3+?

**Comment by chrise86** [comment]
I _assume_ it's going to be a breaking change. There seems to no longer be an option in Xcode to use legacy swift, only to set a global version used throughout the project. As far as I can tell anyway...

I don't really have any way of testing backwards compatibility 😕

**Comment by joshuapinter** [comment]
Okay, no problem. Are you able to add something to the README that at least says that it requires XCode 8.3 or something?

**Comment by joshuapinter** [comment]
@chrise86 Thanks. I'll take a look today.

**Comment by joshuapinter** [comment]
Tested this out locally today, @chrise86. Works great. Can you update the README with the new getGroups method as well and then I'll merge it in and publish a new version to npm. 

Thanks!

**Comment by chrise86** [comment]
No problem, I'm looking into adding more group-related functionality, so was debating holding off from mentioning it here (or rip it out of master) and create a new group-related feature branch with extra groupiness :)

**Comment by joshuapinter** [comment]
@chrise86 Ha!

I'll merge this in and then if you can create a separate branch for the additional groupy goodness, that would be great.

Thanks. 👍

**Pull request merged**
